### ISSUE TITLE
    Resolve-TAPnPPowerShellConflicts doesn't exist

### ISSUE THREAD

**Issue by nicole-ge** [TobiasAT/PowerShell#2]
The cmdlet     Resolve-TAPnPPowerShellConflicts doesn't exist in pnp 2.10.0 PS 7

Can you please help me?

**Comment by TobiasAT** [comment]
Hello @nicole-ge, this command is not part of the PnP PowerShell module, that is the reason why you cannot find the cmdlet.
You can just download the script at https://github.com/TobiasAT/PowerShell/blob/main/Scripts/Resolve-TAPnPPowerShellConflicts.ps1 to resolve the conflicts. 

Here is the documentation about the script: https://github.com/TobiasAT/PowerShell/blob/main/Documentation/Resolve-TAPnPPowerShellConflicts.md

**Comment by nicole-ge** [comment]
Hi @TobiasAT 
So if I understand right, I download your script and run it in my powershell 7 environment? Sorry I am a newbie and try to learn:)

**Comment by TobiasAT** [comment]
@nicole-ge  Yes that is correct. Before you run the script close all your PowerShell sessions (including VS Code), else some files may be in use. Then you can start a new PS7 session and run the script. Should work, used it today after a PnP module update.

**Comment by nicole-ge** [comment]
@TobiasAT ok, I will test it and let you. Thank you very much

**Comment by nicole-ge** [comment]
Yes , it works. thank you 😊

**Comment by TobiasAT** [comment]
Glad that the workaround is working for you too.
